
" In this file, place your personal defaults or system overrides.
" This file is loaded after the Veggieshell vimrc config.

" some common choices:

if has("gui_running")
	"set guifont=6x13
	"set guioptions-=b
endif

" vim:ts=4
