
#
# This file contain all your personal bashrc variables or aliases 
# or other configuration
#

# Your favorite term: eterm, xterm, rxvt, etc. include any options.
# This overrides the Veggieshell defaults.
veggie_term="rxvt -fg grey90 -bg grey10"

# for some machines, DNS gets funky
if [ "$DISPLAY" = "kerplunk:0.0" ]; then
	export DISPLAY=$kerplunk:0
fi

# vim:ts=4:sts=4syntax=sh
